url: "https://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/projet-2-simonpinkas" # the subpath of your site, e.g. /blog
title: "Top 5" # the name of your site, e.g. ACME Corp.

collections:
  albums:
    output: true

plugins:
  - jekyll-admin